### ISSUE TITLE
Consider including a LICENSE file

### ISSUE THREAD

**Issue by lukasoyen** [jackjansen/py-dom-xpath-six#3]
This repository and the package is missing a LICENSE file. It is marked as licensed as MIT, but the package should also ship the license text as part of the distribution.

This would allow https://pypi.org/project/scancode-toolkit/ to classify this correctly as MIT licensed.

**Comment by synapticarbors** [comment]
This would also be helpful for packaging this project via conda-forge: https://github.com/conda-forge/staged-recipes/pull/16884/files
