### ISSUE TITLE
Consider formatting the source with `black`

### ISSUE THREAD

**Issue by lukasoyen** [jackjansen/py-dom-xpath-six#4]
Over the last year, `black` https://github.com/psf/black has emerged as a great automatic python formatter in the python community.

Please consider formatting the source code with it for easier readability. From the readme:

> Black is the uncompromising Python code formatter. By using it, you agree to cede control over
> minutiae of hand-formatting. In return, Black gives you speed, determinism, and freedom from 
> pycodestyle nagging about formatting. You will save time and mental energy for more important 
> matters.

> Blackened code looks the same regardless of the project you're reading. Formatting becomes 
> transparent after a while and you can focus on the content instead.

> Black makes code review faster by producing the smallest diffs possible.

**Comment by jackjansen** [comment]
Finally done.
